services:

  logchain:
    container_name: logchain
    depends_on:
      - ntfy
    build: .
    ports:
      - "8016:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOGCHAIN_PATH}/config/:/app/config/
      - ${LOGCHAIN_PATH}/data/:/app/data/
      - ${LOGCHAIN_PATH}/logs/:/app/logs/
      - ./config.yaml:/app/config.yaml
    environment:
      - LOGCHAIN_SCAN_MINUTES=${LOGCHAIN_SCAN_MINUTES}
      - NTFY_URL=${NTFY_URL}
      - NTFY_TOPIC=${NTFY_TOPIC}
    restart: unless-stopped

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      NTFY_BASE_URL: ${NTFY_URL}
      NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /docker/ntfy:/etc/ntfy
    ports:
      - 8047:80
    restart: unless-stopped
