services:

  logchain-agent:
    build: .
    container_name: logchain_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    environment:
      - NOTIFY_URL=${NOTIFY_URL}
      - LOG_LEVEL=INFO
    restart: unless-stopped
  
  # logchain-web:
  #   build: .
  #   container_name: logchain_web
  #   volumes:
  #   environment:
  #   restart: unless_stoped
