# this file is used to generate mock logs for testing and development

services:
  # log-generator:
  #   image: alpine
  #   container_name: mock-log-producer
  #   command: >
  #     sh -c "while true; do
  #       echo \"$(date --iso-8601=seconds) INFO - Application heartbeat: processing batch ID $$(random_id=$$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8); echo $$random_id)\";
  #       sleep 2;
  #       echo \"$(date --iso-8601=seconds) WARN - High memory pressure detected on node-01\";
  #       sleep 3;
  #       echo \"$(date --iso-8601=seconds) ERROR - Failed to connect to database: connection timeout\";
  #       sleep 5;
  #     done"
  #   restart: always

  web-mock-01:
    image: nginx:alpine
    container_name: nginx-log-producer-01
    ports:
      - "8081:80"
    restart: always

  web-mock-02:
    image: nginx:alpine
    container_name: nginx-log-producer-02
    ports:
      - "8082:80"
    restart: always

  web-mock-03:
    image: nginx:alpine
    container_name: nginx-log-producer-03
    ports:
      - "8083:80"
    restart: always

  web-mock-04:
    image: nginx:alpine
    container_name: nginx-log-producer-04
    ports:
      - "8084:80"
    restart: always

  web-mock-05:
    image: nginx:alpine
    container_name: nginx-log-producer-05
    ports:
      - "8085:80"
    restart: always

  log-generator:
    image: alpine
    container_name: mock-log-producer
    command: >
      sh -c "while true; do
        echo \"$$(date +%Y-%m-%dT%H:%M:%S) INFO Random value: $$((RANDOM % 1000))\";
        sleep 2;
      done"
    restart: always
    
  solar-sim:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: solar-log-producer
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../../:/app
    command: python demo/sim/solar_sim.py
    restart: always
    
  cloud-sim:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: cloud-log-producer
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../../:/app
    command: python demo/sim/cloud_sim.py
    restart: always
